# Generated by Django 3.0.8 on 2020-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='default_product.jpg', upload_to='product_photos')),
                ('category', models.CharField(max_length=200)),
                ('qty_amount', models.CharField(choices=[('250ml', '250ml'), ('500ml', '500ml'), ('1L', '1L'), ('5L', '5L'), ('20L', '20L')], default='250ml', max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
