export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const AUTH_ERROR = "AUTH_ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const GET_EMPLOYEE_DATA = "GET_EMPLOYEE_DATA";
export const ADD_EMPLOYEE_DATA = "ADD_EMPLOYEE_DATA";
export const UPDATE_EMPLOYEE_DATA = "UPDATE_EMPLOYEE_DATA";
export const DELETE_EMPLOYEE_DATA = "DELETE_EMPLOYEE_DATA";

export const GET_INVOICE_DATA = "GET_INVOICE_DATA";
export const ADD_INVOICE_DATA = "ADD_INVOICE_DATA";
export const UPDATE_INVOICE_DATA = "UPDATE_INVOICE_DATA";
export const DELETE_INVOICE_DATA = "DELETE_INVOICE_DATA";

export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const ADD_PRODUCT_DATA = "ADD_PRODUCT_DATA";
export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";
export const DELETE_PRODUCT_DATA = "DELETE_PRODUCT_DATA";

export const TOGGLE_MODAL = "TOGGLE_MODAL";

