# Generated by Django 3.0.8 on 2020-08-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200805_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='phone',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
