# Generated by Django 3.0.8 on 2020-07-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200726_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='employee_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_no',
            field=models.IntegerField(blank=True, default='0700000000'),
        ),
        migrations.CreateModel(
            name='employeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('FINANCE AND ACCOUNTS', 'FINANCE'), ('HR', 'HR'), ('CUSTOMER CARE', 'CUSTOMER CARE'), ('STORES', 'STORES'), ('SALES AND MARKETING', 'SALES AND MARKETING'), ('IT', 'IT'), ('SECURITY', 'SECURITY'), ('CLEANING', 'CLEANING'), ('EXECUTIVE', 'EXECUTIVE')], max_length=50)),
                ('title', models.CharField(choices=[('CEO', 'CEO'), ('HEAD', 'HEAD'), ('MANAGER', 'MANAGER'), ('SENIOR', 'SENIOR'), ('ACCOUNTANT', 'ACCOUNTANT'), ('JUNIOR', 'JUNIOR'), ('GUARD', 'GUARD')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_employed', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_email', to='accounts.employeeProfile')),
                ('image', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_image', to='accounts.employeeProfile')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_phoneNo', to='accounts.employeeProfile')),
            ],
        ),
    ]
