# Generated by Django 3.0.8 on 2020-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200728_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_no',
            field=models.CharField(blank=True, default='0700000000', max_length=10),
        ),
    ]
