# Generated by Django 3.0.8 on 2020-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200728_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='salary',
            field=models.CharField(max_length=10),
        ),
    ]
