# Generated by Django 3.0.8 on 2020-07-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200728_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_email', to='accounts.employeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_image', to='accounts.employeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='phone_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_phoneNo', to='accounts.employeeProfile'),
        ),
    ]
