# Generated by Django 3.0.8 on 2020-07-30 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200728_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_employed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
