# Generated by Django 3.0.8 on 2020-07-30 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200730_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='date_employed',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
