# Generated by Django 3.0.8 on 2020-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200730_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='job_title',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Head', 'HEAD'), ('Manager', 'Manager'), ('Sr', 'Sr'), ('Accountant', 'ACCOUNTANT'), ('Jnr', 'JUNIOR'), ('Guard', 'GUARD'), ('Consultant', 'CONSULTANT')], max_length=50),
        ),
    ]
